### ISSUE TITLE
[Feat]: Support non-docker Actions

### ISSUE THREAD

**Issue by GeekMasher** [42ByteLabs/ghactions#90]
In some cases, a user might want to run their Action as a binary and not a Container image.

```yaml
# ...
runs:
  using: "composite"
  steps:
    - name: "Setting Up Action"
      run: |
        echo "Setup..."

    - name: "Run Action"
      run: |
        # ...
```

https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
